package configx

var SensitiveFields = []string{
	"citizenId",
	"identifierNumber",
	"identificationNumber",
	"identifier",
	"laserId",
	"chipId",
	"firstnameTh",
	"lasstnameTh",
	"firstname",
	"firstName",
	"lastname",
	"lastName",
	"fullname",
	"fullName",
	"thaiFName",
	"thaiLName",
	"firstnameEn",
	"lasstnameEn",
	"engFName",
	"engLName",
	"dateOfBirthTh",
	"dateOfBirthEn",
	"homeAddressNo",
	"homeAddress",
}
