package configx

const (
	CryptoGcmUatKey   = "thisisaeskey16bt"
	CryptoGcmUatNonce = "thisisnoncee"
	CryptoGcmPrdKey   = "kbcptgpm5OegmJN7"
	CryptoGcmPrdNonce = "nlOqfSqvdTj8"
)

var SensitiveFields = []string{
	"citizenId",
	"citizenID",
	"passportID",
	"passportNo",
	"passNum",
	"passportNumber",
	"identifierNumber",
	"identificationNumber",
	"identifier",
	"laserId",
	"chipId",
	"numberUnderImage",
	"firstnameTh",
	"thaiFirstName",
	"lasstnameTh",
	"thaiLastName",
	"firstname",
	"firstName",
	"lastname",
	"lastName",
	"fullname",
	"fullName",
	"thaiFName",
	"thaiLName",
	"firstnameEn",
	"engFirstName",
	"lastNameEn",
	"engLastName",
	"engFName",
	"engLName",
	"spouseNameTh",
	"spouseNameEn",
	"dateOfBirthTh",
	"dateOfBirthEn",
	"homeAddressNo",
	"homeAddress",
	"addressName",
	"officeName",
	"mobilePhone",
	"mobile",
	"officePhone",
	"officePhoneNo",
	"addressLine1",
	"addressLine2",
	"addressLine3",
	"officeAddress1",
	"officeAddress2",
	"officeAddress3",
	"officeAddr1",
	"officeAddr2",
	"officeAddr3",
	"legalAddress1",
	"legalAddress2",
	"legalAddress3",
	"legalAddr1",
	"legalAddr2",
	"legalAddr3",
	"mailingAddress1",
	"mailingAddress2",
	"mailingAddress3",
	"mailingAddr1",
	"mailingAddr2",
	"mailingAddr3",

	"identification_number",
	"chip_id",
	"card_no",
	"firstname_th",
	"lastname_th",
	"firstname_en",
	"lastname_en",
	"date_of_birth_th",
	"date_of_birth_en",
	"floor",
	"home_address_no",
	"home_moo",
	"home_alley",
	"home_soi",
	"home_road",
	"home_sub_district_value",
	"home_district_value",
	// "home_province_value",
	"home_postcode",
	"number_under_image",
}
